### ISSUE TITLE
[suggestion] Add docker option to strapi-starter where user can choose db and setup docker-compose

### ISSUE THREAD

**Issue by rrfaria** [strapi/strapi-starter-next-blog#35]
Like you do on create-strapi-app 
you could add an option like --docker-compose
where ask to users if they want to setup all in docker and add a database on data 
and another good idea and options to setup kubernates

**Comment by remidej** [comment]
Hello!

It sounds like your feedback is about the create-strapi-starter CLI, not this starter in particular.

Can you please open an issue on the [Strapi monorepo](https://github.com/strapi/strapi) instead? All the create-strapi-starter options are configured [there](https://github.com/strapi/strapi/blob/master/packages/create-strapi-starter/create-strapi-starter.js#L13-L26). You can follow the [Feature Request](https://github.com/strapi/strapi/issues/new?assignees=&labels=&template=FEATURE_REQUEST.md) issue template.

In the meantime I'm closing this issue since it's out the starter's scope
